automatic-flight-for-admins: true
automatic-flight-for-player: false

default-gamemode: survival
can-build: false
inventory-locked: true
can-take-damage: false
can-hunger: false
entities-focus-player: false
entity-grief: false
can-mob-spawn: false

drop-items-on-death: false
keep-inventory: true
fire-spread: false
leaf-decay: false
natural-regeneration: false
daylight-cycle: false
weather-cycle: false
announce-advancements: false
advancements-enabled: false

tick-freeze: true
tick-speed: 0

enable-player-name-tag: true

join-messages: default # default, disabled, custom
leave-messages: default # default, disabled, custom

color-settings:
  primary: '#00A4FC'
  secondary: '#00FC00'
  tertiary: '#FCE300'
  danger: '#f90036'
  grey:  '#A8A8A8'

mysql:
  host: 'localhost'
  port: 3306
  database: 'jozelot_network'
  user: ''
  password: ''

redis:
  host: 'localhost'
  port: 6379
  password: ''