#
# JozelotNetwork
#

network-name: 'jozelot.de'
brand-name: '§b§ljozelot.de§r'

punishment-reasons:
  - "101 Hacking"
  - "102 Killaura"
  - "103 Movement"
  - "104 X-Ray"
  - "105 AutoClicker"
  - "106 Reach"
  - "107 Unfairer Vorteil"
  - "201 Beleidigung"
  - "202 Schwere Beleidigung"
  - "203 Rassismus"
  - "204 Spamming"
  - "205 Werbung"
  - "206 Provokation"
  - "207 Wortwahl"
  - "208 Drohung"
  - "209 Radikalismus"
  - "301 Griefing"
  - "302 Scamming"
  - "303 Trolling"
  - "304 Bug Using"
  - "401 Unangemessener Name"
  - "402 Unangemessener Skin"
  - "403 Ban Umgehung"
  - "404 Account Sicherheit"
  - "405 Vortäuschen von Rechten"
  - "406 Sicherheit-Bann"

pterodactyl:
  url: "https://panel.jozelot.de"
  api-key: "KEY"


color-settings:
  primary: '#00A4FC'
  secondary: '#00FC00'
  tertiary: '#FCE300'
  danger: '#f90036'
  grey:  '#A8A8A8'

lobby-server: 'lobby'

# Setup MySQL and Redis Databases
mysql:
  host: 'localhost'
  port: 3306
  database: 'jozelot_network'
  user: ''
  password: ''

redis:
  host: 'localhost'
  port: 6379
  password: ''

# Permissions:
# network.command
# network.command.reload
# network.command.lobby
# network.command.clearchat
# network.command.find
# network.get.logs
# network.clearchat.bypass
# network.network.manage
# network.network.manage.server.start/stop/restart/status

# network.maintenance.bypass.all
# network.maintenance.bypass.<server>
# network.forcedhost.all
# network.forcedhost.<server>
# network.command.ban
# network.command.unban
# network.command.banlist
# network.command.kick
# network.ban.bypass
# network.command.tpo
# network.command.tpohere
# network.command.send
# network.command.server
# network.command.whitelist
# network.whitelist.bypass
# network.command.playtime
# network.command.playtime.admin
# network.command.broadcast
# network.maxplayers.bypass.all
# network.maxplayers.bypass.<server>

# network.command.msg
# network.command.gmsg
# network.command.global
# network.command.reply
# network.chat.minimessage

# UUID operatorUUID = (source instanceof Player p) ? p.getUniqueId() : new UUID(0L, 0L);

#  UUID operatorUUID = (source instanceof Player p) ? p.getUniqueId() : new UUID(0L, 0L);
#            plugin.getMySQLManager().logAction(operatorUUID, "SEND", args[0], "Grund: " + reason + " | Dauer: " + timeArgs);